name: pahe_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Package
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.1
  flutter_native_splash: ^2.2.17
  dio: ^4.0.6
  provider: ^6.0.5
  dartz: ^0.10.1
  carousel_slider: ^4.2.1
  infinite_scroll_pagination: ^3.2.0
  get_it: ^7.2.0
  webview_flutter: ^3.0.4
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Regular.ttf
